### ISSUE TITLE
named files must be .go files

### ISSUE THREAD

**Issue by larryhu** [gpmgo/gopm#107]
gopm build abc.go

output:

[GOPM] 03-02 16:29:15 [ INFO] Building...
[GOPM] 03-02 16:29:15 [DEBUG] Args: [go build abc.go -o abc]
[GOPM] 03-02 16:29:15 [ INFO] Setting GOPATH to /Users/larry/abc/.vendor
[GOPM] 03-02 16:29:15 [ INFO] ===== application outputs start =====

named files must be .go files
[GOPM] 03-02 16:29:16 [ INFO] ====== application outputs end ======
[GOPM] 03-02 16:29:16 [ INFO] Setting GOPATH back to /Users/larry/GOPATH
[GOPM] 03-02 16:29:16 [FATAL] fail to build program: exit status 1

golang 1.8 -o参数应该加在build后面 否则会出现：
named files must be .go files

go build -o abc abc.go

**Comment by Unknwon** [comment]
好坑啊！:sob:

**Comment by larryhu** [comment]
我提交了个 patch 来修复这个小bug 

https://github.com/gpmgo/gopm/pull/108

**Comment by fbens** [comment]
> golang 1.8 -o参数应该加在build后面 否则会出现：
> named files must be .go files
> 
> go build -o abc abc.go

终于找到解决方法了。
