### ISSUE TITLE
更改依赖后重新build不会使用最新依赖

### ISSUE THREAD

**Issue by Cretu** [gpmgo/gopm#110]
需要手动删除.vender后才可以再次link到最新依赖，这是否不太合理啊。 # @

**Comment by Unknwon** [comment]
什么叫做“更改依赖”？

**Comment by Cretu** [comment]
@Unknwon 不好意思，可能我没描述清楚。这里的更改依赖指：修改.gopmfile文件中的依赖包导入配置，比如修改tag为其他版本后执行gopm build并不会重新获取依赖（未下载）build生产可执行文件，手动执行gopm get 后能下载最新依赖， 但不会使用最新依赖编译代码。
BTW：MacOS sierra，go 1.8
