### ISSUE TITLE
无法获取 `grpc`

### ISSUE THREAD

**Issue by tupunco** [gpmgo/gopm#116]
`go get google.golang.org/grpc`
`gopm get google.golang.org/grpc`

` gopm.io` 不提供搜索功能.

**Comment by deporz** [comment]
可以通过翻墙下载GRPC的依赖的,另外两个x/net包里面的`golang.org/x/net/http2`,`golang.org/x/net/trace`

**Comment by zsying** [comment]
google.golang.org/api/drive/v3  类似的  google.golang.org 域名的都没法下载，不知道能否纳入进来。
