### ISSUE TITLE
建议gopm自身能直接编译不依赖github下载

### ISSUE THREAD

**Issue by chatfeed** [gpmgo/gopm#117]
我想用这个是因为go的包管理下不下来，如果gopm也要用的话陷入死循环了

**Comment by excosy** [comment]
先手动git clone依赖包试试

**Comment by chenPengXu** [comment]
go get只是golang.org下的包下载会超时吧，正常github下载没有问题， 如果用gopm，其实它这做的挺，因为gopm是从自己数据仓库下包的，官方文档有
