### ISSUE TITLE
拉取文件无法自定local gopath

### ISSUE THREAD

**Issue by kooksee** [gpmgo/gopm#119]
｀gopm get -l ｀无法根据gopmfile的配置里面的gopath路径拉取，每次执行｀gopm get -l｀都会拉取到当前文件夹，怎么回事？？

**Comment by chenPengXu** [comment]
gopm get源码里看并不是根据配置获取，而还是list一样进行了分析的。 我这两天提了一个修改版本，一是增加了子包分析，二是这个get根据配置文件获取，你可以看看。
或者用golang 1.12版本吧，该版本的go mod我用了，还行
