### ISSUE TITLE
gopm get  不下载新的依赖

### ISSUE THREAD

**Issue by bensinos** [gpmgo/gopm#120]
项目原依赖：

github.com/gorilla/websocket = tag:v1.2.0
github.com/astaxie/beego = tag:v1.9.2
github.com/go-xorm/xorm = tag:v0.6.4
github.com/go-sql-driver/mysql = tag:v1.3
github.com/jlaffaye/ftp = commit:299b7ff5b6096588cceca2edc1fc9f557002fb85
github.com/robfig/cron = tag:v1

新增一个依赖
github.com/natefinch/lumberjack = tag:v2.0

执行gopm get -g -v
[GOPM] 01-17 15:19:58 [ INFO] App Version: 0.8.8.0307 Beta
[GOPM] 01-17 15:19:58 [ INFO] Local repository path: /Users/hufayou/.gopm/repos
[GOPM] 01-17 15:19:58 [ INFO] Indicated GOPATH: /Users/hufayou/Documents/gowork
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/astaxie/beego.v1.9.2
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/astaxie/beego@tag:v1.9.2
[GOPM] 01-17 15:19:58 [ WARN] Package in GOPATH has version control: github.com/astaxie/beego
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/go-sql-driver/mysql.v1.3
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/go-sql-driver/mysql@tag:v1.3
[GOPM] 01-17 15:19:58 [ WARN] Package in GOPATH has version control: github.com/go-sql-driver/mysql
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/go-xorm/xorm.v0.6.4
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/go-xorm/xorm@tag:v0.6.4
[GOPM] 01-17 15:19:58 [ INFO] Package copied to GOPATH: github.com/go-xorm/xorm
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/gorilla/websocket.v1.2.0
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/gorilla/websocket@tag:v1.2.0
[GOPM] 01-17 15:19:58 [ WARN] Package in GOPATH has version control: github.com/gorilla/websocket
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/jlaffaye/ftp.299b7ff5b6096588cceca2edc1fc9f557002fb85
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/jlaffaye/ftp@commit:299b7ff5b6096588cceca2edc1fc9f557002fb85
[GOPM] 01-17 15:19:58 [ WARN] Package in GOPATH has version control: github.com/jlaffaye/ftp
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/github.com/robfig/cron
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: github.com/robfig/cron@branch:<UTD>
[GOPM] 01-17 15:19:58 [ WARN] Package in GOPATH has version control: github.com/robfig/cron
[GOPM] 01-17 15:19:58 [ INFO] /Users/hufayou/.gopm/repos/golang.org/x/text
[GOPM] 01-17 15:19:58 [DEBUG] Skipped installed package: golang.org/x/text@branch:<UTD>
[GOPM] 01-17 15:19:59 [ INFO] Package copied to GOPATH: golang.org/x/text
[GOPM] 01-17 15:19:59 [ INFO] 0 package(s) downloaded, 0 failed

从日志可以看到，完全跳过了新增的依赖。求解。。。

**Comment by Unknwon** [comment]
github.com/natefinch/lumberjack 如果项目本身没引用的话，你添加了配置也是不会拉下来的。。
