### ISSUE TITLE
gopm get 错误：dial tcp: i/o timeout

### ISSUE THREAD

**Issue by excosy** [gpmgo/gopm#122]
日志如下，该地址通过curl是可以正常访问的

{12:19}~ ➭ gopm get github.com/revel/revel
[GOPM] 02-11 12:20:38 [ WARN] No GOPATH setting available
[GOPM] 02-11 12:21:08 [ERROR] github.com/revel/revel: fail to make request: Get https://gopm.io/api/v1/revision?pkgname=github.com/revel/revel: dial tcp: i/o timeout
{12:21}~ ➭ curl https://gopm.io/api/v1/revision\?pkgname\=github.com/revel/revel
{"sha":"07d67722d092b5f75865a332ed1a26a5f78e55e5"}%                                                                                                                                                                                        {12:21}~ ➭

**Comment by Unknwon** [comment]
这个。。就是。。网络连接不通畅啦。
