### ISSUE TITLE
cannot find revision in page: github.com/golang/net

### ISSUE THREAD

**Issue by caorushizi** [gpmgo/gopm#123]
cannot find revision in page: github.com/golang/net

**Comment by chenzeshu** [comment]
the same question, any help

**Comment by NexusLee** [comment]
cannot find revision in page: github.com/golang/sys

**Comment by LiJoah** [comment]
I have the same problem，Is there a solution? thanks!   > "golang.org/x/text: cannot find revision in page: github.com/golang/text
"

**Comment by zinc357** [comment]
the same question. 
golang.org/x/tools/cmd/goimports: cannot find revision in page: github.com/golang/tools

**Comment by Unknwon** [comment]
Should be fixed by now!
