### ISSUE TITLE
使用GOPATH=./tmp gopm get -g -d golang.org/x/sys/unix，报错文件目录已经存在。。

### ISSUE THREAD

**Issue by qylixin** [gpmgo/gopm#126]
执行命令：
GOPATH=./tmp gopm get -g -d golang.org/x/sys/unix
报错信息：
[GOPM] 08-07 03:14:16 [ERROR] %!(EXTRA string=Fail to copy to GOPATH:)
[GOPM] 08-07 03:14:16 [FATAL] %!(EXTRA string=	file or directory alreay exists: /opt/gopath/src/github.com/hyperledger/fabric/.build/gotools/src/golang.org/x/sys)
相关操作：
第1次执行时正确，第2次执行时报以上错误，第3次执行时又正确，第4次又报错，依次类推。。。

**Comment by Unknwon** [comment]
.... 你这个操作好诡异啊，能不能正常设置 gopath
