### ISSUE TITLE
gopm get -g -v github.com/micro/micro  

### ISSUE THREAD

**Issue by shabbyboy** [gpmgo/gopm#140]
gopm get -g -v github.com/micro/micro 
error:
[GOPM] 03-21 17:00:23 [FATAL] fail to list imports(github.com/hashicorp/vault): fail to get imports(github.com/hashicorp/vault-plugin-auth-alicloud): cannot find package "github.com/hashicorp/vault-plugin-auth-alicloud" in any of:
	/usr/local/go/src/github.com/hashicorp/vault-plugin-auth-alicloud (from $GOROOT)
	/var/folders/r_/7cddhvks1qj7w_s4rpmc2t8c0000gn/T/528234000/src/github.com/hashicorp/vault-plugin-auth-alicloud (from $GOPATH)
	/Users/tugame/go/src/github.com/hashicorp/vault-plugin-auth-alicloud

**Comment by yanshinian** [comment]
me too

gopm get -v -u  github.com/micro/examples/greeter/srv
