### ISSUE TITLE
go mod 能否用 gopm.io 的资源？

### ISSUE THREAD

**Issue by lluck42** [gpmgo/gopm#144]
gopm下载资源挺方便的，之前一直都是直接 git clone，
现在是用 go mod 来管理，用 gopm 来下载
go mod 能否用 gopm.io 的资源？

这是一个提问（点不到按钮）

**Comment by kusora** [comment]
go mod 就可以自己搭建goproxy了

**Comment by Unknwon** [comment]
楼上老哥正解了，有了国内直通的goproxy，gopm.io 可以退休了！

**Comment by aofei** [comment]
无闻大哥对这种事儿看得好开……👍话说大哥可以用 [goproxy.cn](https://goproxy.cn) 作上游然后在 [gopm.io](https://gopm.io) 也搭一个 GOPROXY 服务，毕竟 [gopm.io](https://gopm.io) 知名度还是相当高的。[goproxy.cn](https://goproxy.cn) 我已经捐给七牛云啦，连域名都过户去了，前两天刚交接完，许叔推动的，现在已经跑在七牛云平台了，很快也很稳定，可以放心用做上游的。搭建 GOPROXY 服务的话还可以考虑用 [Goproxy](https://github.com/goproxy/goproxy) 这个项目，比 Athens 轻量级些，可以直接当成包用。:-)

向前辈致敬！😠

**Comment by unknwon** [comment]
哈哈，goproxy.cn 好啊，老许推的那问题不大！ 我会在 README 和网站挂上 take down 日期。
