### ISSUE TITLE
gopm bin不能自动下载依赖包(command "gopm bin" could not  auto download depends lib)

### ISSUE THREAD

**Issue by maxid** [gpmgo/gopm#49]
gopm bin不能自动下载依赖包(command "gopm bin" could not  auto download depends lib)

gopm bin gogs
[GOPM] 14-11-18 22:41:44 [FATAL] package not installed: github.com/go-xorm/core @ commit:3e0fa232ab

**Comment by LyricTian** [comment]
## gopm install ERROR:[FATAL] package not installed: github.com/martini-contrib/sessions
### go install 编译通过
