### ISSUE TITLE
同个project下多个target的情况

### ISSUE THREAD

**Issue by samuelyao314** [gpmgo/gopm#54]
我的目录结构是

tencent
├── apps
│   └── webpcld
├── golib
│   ├── bus.go
│   ├── router.go
│   └── tsf4g_base
├── output
├── util
│   ├── api_response.go
│   ├── byte_base10.go
│   ├── http_server.go
│   ├── tcp_server.go
│   └── wait_group_wrapper.go
├── webpcl
│   ├── context.go
│   ├── http.go
│   ├── options.go
│   ├── session.go
│   ├── tcp.go
│   └── webpcl.go

tencent是我的项目根路径。app/webpcld是一个服务的main函数所在的文件。webpcl是webpcld的具体逻辑代码。util是公共代码。在tencent下的.gomfile的内容是

[target]
path = tencent

[deps]
github.com/qiniu/iconv =
github.com/qiniu/log =
github.com/mreiferson/go-options =
github.com/BurntSushi/toml =
tencent/webpcl =

[res]
include =

在app/webpcld下，执行

samuel@localhost:~/tencent/apps/webpcld$ gopm build -v
[GOPM] 15-01-29 19:50:11 [ INFO] App Version: 0.8.5.1125 Beta
[GOPM] 15-01-29 19:50:11 [ INFO] Local repository path: /home/samuel/.gopm/repos
[GOPM] 15-01-29 19:50:11 [ WARN] No GOPATH setting available
[GOPM] 15-01-29 19:50:11 [DEBUG] Linking webpcld...
[GOPM] 15-01-29 19:50:11 [DEBUG] Loading dependencies...
[GOPM] 15-01-29 19:50:11 [FATAL] package not installed: tencent/webpcl

无法正常的编译啊。 我希望的是.gomfile 在项目的根目录下。main所在的文件在哪里都没有关系。这样才能公用代码。

第2个问题是：妥协下，把app/webpcld/webpcld.go 文件移到根目录下。再次执行

samuel@localhost:~/tencent$ gopm build -v  webpcld.go
[GOPM] 15-01-29 19:43:32 [ INFO] App Version: 0.8.5.1125 Beta
[GOPM] 15-01-29 19:43:32 [ INFO] Local repository path: /home/samuel/.gopm/repos
[GOPM] 15-01-29 19:43:32 [ WARN] No GOPATH setting available
[GOPM] 15-01-29 19:43:32 [DEBUG] Linking tencent...
[GOPM] 15-01-29 19:43:32 [DEBUG] Loading dependencies...
[GOPM] 15-01-29 19:43:32 [DEBUG] Linking github.com/qiniu/log...
[GOPM] 15-01-29 19:43:32 [ INFO] Guess import path: /home/samuel/tencent
[GOPM] 15-01-29 19:43:32 [DEBUG] Linking github.com/qiniu/iconv...
[GOPM] 15-01-29 19:43:32 [ INFO] Guess import path: /home/samuel/tencent
[GOPM] 15-01-29 19:43:32 [FATAL] package not installed: C

因为在我的代码 golib/bus.go  中，使用了cgo
import "C"

这个不应该报错的。

**Comment by tomasky** [comment]
gopm和go差别在哪里？，构建的源代码目录都不能指定。

**Comment by Unknwon** [comment]
你不给参数默认 main 包就是当前目录，所以你要切到子目录下去构建，也就是目前来说需要多个 .gopmfile。。。
