### ISSUE TITLE
A question about unit test deps and .gopm file

### ISSUE THREAD

**Issue by szank** [gpmgo/gopm#55]
Hi, 
I a trying to use gopm in my current project, but I have a few issues. 
1. There is no unit test dependencies in .gopm file. I have cloned the project, added test flag to the gopm gen command, and made it show up in .gopm file. but no luck with making them download yet. 
2. Is is by design that manually adding dependency to .gopm file doesn't work ?  
   First I tried to add test dependency manually to .gopm file, and then call gopm get, but it wasn't downloaded. ( I have removed it from my $GOPATH before ) [UPDATE: I have dug deeper in the code and now I understand how it works ]
3. Could you please add some more documentation on how does this tool work, current limitations, etc. so people won't have to dig through the code for that ?

I would like to submit few patches, to add things I need, but I want them to be compliant with the tool's design philosophy.

**Comment by Unknwon** [comment]
Hi, hmm, this need some code work, add to .gopmfile leads to specify the version of package when needed, but gopm does not link test dep when actually testing, so even you downloaded the package, it's still looks like you didn't have it. I think this is a bug.
