### ISSUE TITLE
Transitive dependencies

### ISSUE THREAD

**Issue by szank** [gpmgo/gopm#57]
Hi, I have another question. It is unrelated to previous ones, so I created new issue. 

In my project I am using martini (https://github.com/go-martini/martini)
martini is depending on go built in libraries and inject (https://github.com/codegangsta/inject). 

Do you plan to handle transitive dependencies such as those ? I believe that they need to be in .gopm file.

**Comment by Unknwon** [comment]
I believe the same thing, too. :)
