### ISSUE TITLE
cannot find locater in page

### ISSUE THREAD

**Issue by firewut** [gpmgo/gopm#58]
Got this error while
```bash
gopm get
```

```bash
github.com/gorilla/mux: cannot find locater in page: github.com/gorilla/mux
github.com/coderhaoxin/handlebars: cannot find locater in page: github.com/coderhaoxin/handlebars
```

What's happened ?:D

**Comment by Unknwon** [comment]
Hmm.. might because network error and got a wrong page...

**Comment by firewut** [comment]
Got it today's morning :D

**Comment by Unknwon** [comment]
gopm use regex to find commit SHA in GitHub page, so if somehow whatever returns isn't complete, error occurs.

**Comment by lauyoume** [comment]
我也是遇到这个问题了，无法下载github.com的包
[ERROR] github.com/bitly/nsq: cannot find locater in page: github.com/bitly/nsq

**Comment by Unknwon** [comment]
@lauyoume 看来是github UI 更新了。。我处理下，多谢反馈

**Comment by Unknwon** [comment]
@lauyoume @firewut 线上版本已经修复！
