### ISSUE TITLE
【新手问题】怎么配合revel使用gopm呢？

### ISSUE THREAD

**Issue by xuxiangyang** [gpmgo/gopm#59]
大神们，最近在研究revel。想配合使用一个golang的包管理工具。我该怎么使用呢？进入项目目录后使用gopm gen会有 warn Getting imports: no buildable Go source files。。
新手，求指导。或者说应该是什么样的目录格式呢？

**Comment by zhuchaowe** [comment]
同问 如何使用revel的打包工具

**Comment by xuxiangyang** [comment]
@zhuchaowe 后来我用了godep，感觉还不错。
