### ISSUE TITLE
semver ranges in .gopm file

### ISSUE THREAD

**Issue by SpainTrain** [gpmgo/gopm#61]
Would you consider (or do you already plan for) allowing semver ranges (e.g., https://github.com/npm/node-semver#ranges) in the `.gopm` file in addition to static tags?

The obvious benefit is being able to keep libraries up-to-date automatically while avoiding bringing in breaking changes.

**Comment by jamescmartinez** [comment]
+1

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

semver ranges is good and I like it, too.

But how do we maintain the range? Go packages does not have this kind of tag that we can use directly, all packages need to be added manually, it would be almost possible work.

Best regards,

**Comment by SpainTrain** [comment]
It could work the same as it does with Bower, which also uses git tags to identify versions (http://bower.io/docs/creating-packages/#register).  Just list the git tags for the relevant repository and choose the highest semver range match.

**Comment by Unknwon** [comment]
@SpainTrain thanks! Looks a good idea, let me do some experiments first!

**Comment by SpainTrain** [comment]
k, let me know if I can help in any way
