### ISSUE TITLE
能不能支持 gopm get --save 功能

### ISSUE THREAD

**Issue by guileen** [gpmgo/gopm#64]
npm 有一个功能是 `npm install --save express`， 在安装了express的同时，还会在 package.josn 中加入 express 的依赖，并且这个依赖是绑定了当前的express版本的，就像 `"express":"^3.0.1"`

gopm 是否也可以加入类似功能，在get完之后，加入到deps，同时把 commit信息记录下来。

**Comment by Unknwon** [comment]
感觉是个不错的功能。。
