### ISSUE TITLE
gopm get error

### ISSUE THREAD

**Issue by beyondblog** [gpmgo/gopm#70]
貌似还是不能导入google的包？
```
[ERROR] code.google.com/p/go.crypto: Should use import path golang.org/x/...
```

**Comment by Unknwon** [comment]
This is error return by Go tool, gopm cannot anything with it. https://docs.google.com/document/d/1jVFkZTcYbNLaTxXD9OcGfn7vYv5hWtPx9--lTx1gPMs/edit

**Comment by beyondblog** [comment]
看上去我似乎只要换个1.3的版本就行!

thx!

**Comment by Unknwon** [comment]
Yes, starts with Go 1.4, it has annoying import path check.
