### ISSUE TITLE
change local repository path

### ISSUE THREAD

**Issue by fanningert** [gpmgo/gopm#71]
Hi,
is it possible to change the path to the "Local repository" per parameter or variable?

**Comment by Unknwon** [comment]
It's currently impossible, but I shall take some time to fix issues in Gopm.... :sob:

**Comment by amery** [comment]
can you consider disabling "local repository" too? I want to use a docker container as builder so `$HOME` is volatile so it would be amazing if gopm could simply `git reset --hard` in place

**Comment by Foxswily** [comment]
I need change local repository path too, do you have any plan to implement is function?
maybe  a global setting file is enough.
