### ISSUE TITLE
Test verbose not printing logs

### ISSUE THREAD

**Issue by jorge8713** [gpmgo/gopm#73]
There seems to be a problem with using
```
gopm test -v
```
The logs from `.Log()` do not show up.

Any help would be appreciated.
Thank you

**Comment by codnee** [comment]
I'd like to take a look at this.

Can you provide the file you are testing?
Is the test passing or failing?

**Comment by paulallen8713** [comment]
**Example of Problem**

foo_test.go
```
package foo

import (
    "fmt"
    "testing"
)

func TestFoo(t *testing.T) {
    fmt.Println("Hello")
    t.Log("World")
}
```

*Using go*:
```
$ go test -v
```
*Output*:
``` 
=== RUN   TestFoo
Hello
--- PASS: TestFoo (0.00s)
	foo_test.go:10: World
PASS
ok  	_/.../.../Desktop	0.010s
```

*Using gopm*:
```
$ gopm test -v
```
*Output*:
```
[GOPM] 15-10-20 15:32:05 [ INFO] App Version: 0.8.6.1228 Beta
[GOPM] 15-10-20 15:32:05 [ INFO] Local repository path: /Users/.../.gopm/repos
[GOPM] 15-10-20 15:32:05 [ INFO] Indicated GOPATH: /Users/.../.go
[GOPM] 15-10-20 15:32:05 [DEBUG] Linking Desktop...
[GOPM] 15-10-20 15:32:05 [DEBUG] Loading dependencies...
[GOPM] 15-10-20 15:32:05 [ INFO] Testing...
[GOPM] 15-10-20 15:32:05 [ INFO] Setting GOPATH to /Users/.../Desktop/.vendor
[GOPM] 15-10-20 15:32:05 [ INFO] ===== application outputs start =====

Hello
PASS
ok  	_/Users/.../Desktop	0.009s
[GOPM] 15-10-20 15:32:05 [ INFO] ====== application outputs end ======
[GOPM] 15-10-20 15:32:05 [ INFO] Setting GOPATH back to /Users/.../.go
[GOPM] 15-10-20 15:32:05 [ INFO] Command executed successfully!
```

**Comment by abelino** [comment]
@Unknwon any chance you can look into this?

**Comment by codnee** [comment]
The logs are only printed when you pass the -v flag to `go test

**Comment by Unknwon** [comment]
Hi all, I've pushed a quick fix to pass `-v` flag to `go test` command.

**Comment by abelino** [comment]
This seems to be fixed, however running `gopm update` doesn't seem to update gopm... I ended up using `go get -u github.com/gpmgo/gopm` to force update. You can mark this issue as closed @Unknwon and thanks for the support.

**Comment by Unknwon** [comment]
@abelino oh! right, I haven't updated the version on the web for gopm.

PS: I can't believe gopm is still working...

**Comment by codnee** [comment]
@Unknwon shouldn't this be closed?

**Comment by abelino** [comment]
Yes please close!

**Comment by Unknwon** [comment]
:blush:
