### ISSUE TITLE
Binaries missing?

### ISSUE THREAD

**Issue by dkreuer** [gpmgo/gopm#76]
I've tried to access the links mentioned in the master/README.md http://gobuild.io/github.com/gpmgo/gopm and http://gobuild.io but all I can see is an error page of Heroku. Are binaries and the gobuild system gone? Just broken?

Tried to compile gopm in OSX by myself but failed too ...

**Comment by Unknwon** [comment]
Hmm.. http://gobuild.io is down for quite a while, no good replace at the moment.

**Comment by codeskyblue** [comment]
:cry:
