### ISSUE TITLE
在用gopm run命令的时候，因为我写code也需要解析命令行参数，用gopm run会显示gopm run的help

### ISSUE THREAD

**Issue by doublelduob** [gpmgo/gopm#78]
在用gopm run命令的时候，因为我写code也需要解析命令行参数，用gopm run会显示gopm run的help

**Comment by Unknwon** [comment]
额。。。有例子没有

**Comment by doublelduob** [comment]
比如  gopm run  mycommand  -v  -c file.conf

**Comment by Unknwon** [comment]
这个情况我建议还是先build再run把。。

**Comment by doublelduob** [comment]
好的，但是go run 是可以的，先build在run，这个体验比较差，我只能用gopm把依赖下载到GOPATH，然后继续用go run

2015-11-28 7:45 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
gopm更侧重依赖下载嗯。。
