### ISSUE TITLE
 Gopm: command not found

### ISSUE THREAD

**Issue by brucefengnju** [gpmgo/gopm#81]
MacOS

install gopm with code:
```
go get -u github.com/gpmgo/gopm

```

and find gopm file in /usr/local/go/bin/bin/gopm

**Comment by Unknwon** [comment]
I think you did not set $GOPATH right, what is value of it?

**Comment by brucefengnju** [comment]
@Unknwon /usr/local/go/bin

**Comment by Unknwon** [comment]
You should set it to `/usr/local/go`

**Comment by brucefengnju** [comment]
@Unknwon I'm confused, /usr/local/go is GOROOT, GOPATH can't be same with GOROOT

**Comment by brucefengnju** [comment]
@Unknwon  I reset GOPATH to other folder. It works now. tks

**Comment by Unknwon** [comment]
You should be confused.

Yes, GOPATH should not be same as GOROOT. But it does not mean `bin` either. :sweat_smile:
