### ISSUE TITLE
目前不支持proxy代理

### ISSUE THREAD

**Issue by kingfs** [gpmgo/gopm#82]
我这里有个需求是需要经过代理下载，git本身设置http_proxy以后不好使，我就想试试gopm，结果也不行，后来我简单粗暴的修改了一些代码，就可以支持代理下载了，但我不是特别熟悉gopm架构，我认为可以专门抽出一层用来封装http下载

文件:gopm\modules\doc\struct.go
增加一个函数：
func httpGet(urls string) (resp *http.Response, err error) {
    proxy_url, _ := url.Parse("http://username:password@proxy_host:proxy_port")
    transport := &http.Transport{Proxy: http.ProxyURL(proxy_url)}
    client := &http.Client{Transport: transport}
    req, err := http.NewRequest("GET", urls, nil)
    fmt.Println(urls)
    if err != nil {
        log.Fatal(err.Error())
    }
    resp, err = client.Do(req)
    return
}
然后我修改func (n *Node) DownloadGopm(ctx *cli.Context)
//      resp, err := http.Get(fmt.Sprintf("%s%s?pkgname=%s",
        //          setting.RegistryUrl, setting.URL_API_REVISION, n.RootPath))
        resp, err := httpGet(fmt.Sprintf("%s%s?pkgname=%s",
            setting.RegistryUrl, setting.URL_API_REVISION, n.RootPath))

**Comment by Unknwon** [comment]
一直支持只是好像文档没写0 0 https://github.com/gpmgo/gopm/blob/master/cmd/config.go#L30

**Comment by kingfs** [comment]
好像不能用啊~~我之前试过http_proxy设置，不能用，所以我才改了一下

**Comment by Unknwon** [comment]
这。。好吧。。

**Comment by kingfs** [comment]
内网环境里面，你懂得，下载代码库太麻烦了

应该可以封装一下http请求，把proxy这些信息加入，这样所有的操作都可以支持proxy啦

**Comment by Unknwon** [comment]
嗯。。这就奇怪了。。莫非代码里允许设置但是实际上没用代理后的值。。

**Comment by kingfs** [comment]
我刚刚接触go，不清楚http.Get这样的调用能否直接支持proxy。

目前我看到的代码，支持proxy 的http 请求都需要先初始化httpclient，然后配置好请求参数后，调用client.Do(request)发送请求
