### ISSUE TITLE
出现no buildable Go source files问题怎么解决,谢谢

### ISSUE THREAD

**Issue by shawnye** [gpmgo/gopm#87]
<pre>
g:\dev\go\lib\bin>gopm.exe get golang.org/x/mobile
[GOPM] [36m02-23 16:26:31[0m [[33m WARN[0m] Getting imports: no buildable Go source files in C:\
Users\ADMINI~1\AppData\Local\Temp\2\199854200\src\golang.org\x\mobile
</pre>

其中GOPATH=g:\dev\go\lib

**Comment by Unknwon** [comment]
说明这个目录本来。。就没文件，这就是是WARN 吧
