### ISSUE TITLE
RFE: freeze command: specify known good git sha's to be used

### ISSUE THREAD

**Issue by ibotty** [gpmgo/gopm#89]
Maybe that's already possible in some way or another, but I did not find it in the documentation.

To have reproducable builds, it would be great to be able to record the version (commit sha/tag) of all dependencies. That file could be checked into the projects repository, so one does not have to include all the dependencies in the repo (as submodule/subtree or copy).

**Comment by Unknwon** [comment]
This? https://github.com/gpmgo/docs/blob/master/en-US/Gen.md

**Comment by ibotty** [comment]
Yes. Exactly! Would you commit such a file before making a release for gogs? That would make my life easier.

**Comment by Unknwon** [comment]
Yes.
