### ISSUE TITLE
希望gopm支持转发

### ISSUE THREAD

**Issue by helphi** [gpmgo/gopm#90]
- gom 支持转发，可以在 Gomfile 中使用 `gom 'github.com/username/repository', :command => 'git clone http://example.com/repository.git'`
- 希望 gopm 也能支持类似的功能，并且和升级后的 `http://gopm.io` 集成起来，比如在 gopmfile 中使用 `golang.org/x/tools = tag:v1.0.0 = gopm.io/golang.org/x/tools` gopm 就去调用 `git clone http://gopm.io/golang.org/x/tools.git`
- 有了这个功能后，gopm 是不是会比 gom + gopkg.in 更强大呢！？并且大家以后还可以把 `http://gopm.io` 架设到公司内部，就和使用 maven 中央仓库一样那就完美了。

**Comment by Unknwon** [comment]
听起来好强大。。
